Repository ttalkkag/android, pull requests merged in 2024-09, with the labels that each got.

#5 [FEAT/#3] xml 수정
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/res/layout/fragment_calendar_add.xml
Labels: 임홍재, UI⭐

#11 [ADD] 기본 세팅 수정
  app/build.gradle.kts
  app/src/androidTest/java/icon2/ttalkkag/service/ExampleInstrumentedTest.kt
  app/src/main/java/icon2/ttalkkag/TTALKKAGApplication.kt
  app/src/main/java/icon2/ttalkkag/data/dto/BaseResponse.kt
  app/src/main/java/icon2/ttalkkag/data/dto/request/TestRequest.kt
  app/src/main/java/icon2/ttalkkag/data/dto/response/TestResponse.kt
  app/src/main/java/icon2/ttalkkag/data/repositoryImpl/TestRepositoryImpl.kt
  app/src/main/java/icon2/ttalkkag/data/service/TestService.kt
  app/src/main/java/icon2/ttalkkag/di/NetworkModule.kt
  app/src/main/java/icon2/ttalkkag/di/RepositoryModule.kt
  app/src/main/java/icon2/ttalkkag/di/ServiceModule.kt
  app/src/main/java/icon2/ttalkkag/domain/model/TestModel.kt
  app/src/main/java/icon2/ttalkkag/domain/repository/TestRepository.kt
  app/src/main/java/icon2/ttalkkag/presentation/MainActivity.kt
  app/src/main/java/icon2/ttalkkag/presentation/base/BaseActivity.kt
  app/src/main/java/icon2/ttalkkag/presentation/base/BaseDialogFragment.kt
  app/src/main/java/icon2/ttalkkag/presentation/base/BaseFragment.kt
  app/src/main/java/icon2/ttalkkag/presentation/calendarAdd/CalendarAddFragment.kt
  app/src/main/java/icon2/ttalkkag/presentation/home/HomeFragment.kt
  app/src/main/java/icon2/ttalkkag/presentation/mypage/MypageFragment.kt
  app/src/main/java/icon2/ttalkkag/presentation/test/TestActivity.kt
  app/src/main/java/icon2/ttalkkag/presentation/test/TestViewModel.kt
  app/src/main/java/icon2/ttalkkag/util/extension/ContextExt.kt
  app/src/main/java/icon2/ttalkkag/util/extension/FragmentExt.kt
  app/src/main/java/icon2/ttalkkag/util/extension/LifecycleOwnerExt.kt
  app/src/main/java/icon2/ttalkkag/util/extension/ViewExt.kt
  app/src/main/java/icon2/ttalkkag/util/network/HandleApi.kt
  app/src/main/java/icon2/ttalkkag/util/network/NetworkConnectionChecker.kt
  app/src/main/java/icon2/ttalkkag/util/network/NetworkResult.kt
  app/src/test/java/icon2/ttalkkag/service/ExampleUnitTest.kt
Labels: 김승혁, ADD ➕

#8 [UI/#6] Calender add / UI 구현
  app/src/main/res/drawable/shape_rect_10_3e8bff_fill.xml
  app/src/main/res/drawable/shape_rect_10_white000_fill_3e8bff_line.xml
  app/src/main/res/layout/fragment_calendar_add.xml
Labels: 임홍재, UI⭐

#14 [UI/#4] splash login signup 뷰 / UI 구현
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/appearances.xml
Labels: 김재현, UI⭐
